export const PRODUCT_REQUEST_OFFER_ADMIN = "PRODUCT_REQUEST_OFFER_ADMIN";

export const CLOSE_REQUEST = "CLOSE_REQUEST";
export const EXPIRE_OFFER = "EXPIRE_OFFER";
export const GET_PRODUCT_REQUEST_OFFER_ADMIN = "GET_PRODUCT_REQUEST_OFFER_ADMIN";
export const GET_PRODUCT_REQUEST_OFFER_ADMIN_BY_ID = "GET_PRODUCT_REQUEST_OFFER_ADMIN_BY_ID";
export const GET_PRODUCT_REQUEST_OFFERS_BY_REQUEST_ID = "GET_PRODUCT_REQUEST_OFFERS_BY_REQUEST_ID";
export const VERIFY_PAYMENT = "VERIFY_PAYMENT";
export const MAKE_DELIVERED = "MAKE_DELIVERED";
export const SEND_OFFER_TO_BUYER = "SEND_OFFER_TO_BUYER";
export const UPDATE_PRODUCT_REQUEST_OFFER_ADMIN = "UPDATE_PRODUCT_REQUEST_OFFER_ADMIN";