import React from "react";
import { LuGitPullRequest, LuPackageOpen, LuTicketPercent } from "react-icons/lu";
import { BsBoxSeam } from "react-icons/bs";
import { MdOutlineCategory, MdOutlineProductionQuantityLimits, MdRule, MdPoll, MdLocalShipping, MdProductionQuantityLimits, MdStorefront } from "react-icons/md";
import { RiBloggerLine, RiPagesLine } from "react-icons/ri";
import { BiCategoryAlt } from "react-icons/bi";
import { FaRegUser, FaRegQuestionCircle } from "react-icons/fa";
import { SiPagespeedinsights } from "react-icons/si";
import { FiUsers } from "react-icons/fi";
import { HiOutlineOfficeBuilding } from "react-icons/hi";

// NOTE: Pure data extraction from `DesktopSidebar.tsx` to keep UI/behavior identical.
export const desktopSidebarMenuData: any[] = [
  {
    id: 1,
    isNew: false,
    menuTitle: "مدیریت درخواست ها",
    order: "1",
    role: ["admin", "client", "reservation"],
    notif: "",
    menus: [
      {
        path: "/",
        title: "درخواست های مناقصه",
        icon: <LuGitPullRequest className="text-2xl" />,
        id: 110,
        isNew: false,
        subRoutes: [],
        notif: "",
        role: ["admin", "client", "reservation"],
      },

      {
        path: "/pending-orders-financial",
        title: "سفارشات در انتظار تایید مالی",
        icon: <LuPackageOpen className="text-2xl" />,
        id: 240,
        isNew: false,
        subRoutes: [],
        notif: "",
        role: ["admin", "client", "reservation"],
      },
      {
        path: "/product-requests",
        title: "تاریخچه درخواست های مناقصه",
        icon: <LuGitPullRequest className="text-2xl" />,
        id: 241,
        isNew: false,
        subRoutes: [],
        notif: "",
        role: ["admin", "client", "reservation"],
      },
      {
        path: "/shop-management",
        title: "فروشگاه",
        icon: <MdStorefront className="text-2xl" />,
        id: 242,
        isNew: false,
        subRoutes: [],
        notif: "",
        role: ["admin", "client", "reservation"],
      },
    ],
  },

  {
    id: 12,
    isNew: false,
    menuTitle: "فرم های پایه",
    order: "1",
    role: ["admin", "client", "reservation"],
    notif: "",
    menus: [
      {
        path: "/product-request-status",
        title: "مدیریت وضعیت درخواست ها",
        icon: <MdProductionQuantityLimits className="text-2xl" />,
        id: 230,
        isNew: false,
        subRoutes: [],
        notif: "",
        role: ["admin", "client", "reservation"],
      },
      {
        path: "/",
        title: "مدیریت کاربران",
        icon: <FaRegUser className="text-2xl" />,
        id: 2436552,
        isNew: false,
        subRoutes: [
          {
            path: "/role-management",
            title: "مدیریت نقش",
            icon: <MdRule className="text-2xl" />,
            id: 24362,
            isNew: false,
            subRoutes: [],
            notif: "",
            role: ["admin", "client", "reservation"],
          },
          {
            path: "/users-management",
            title: "مدیریت کاربران",
            icon: <FiUsers className="text-2xl" />,
            id: 24389662,
            isNew: false,
            subRoutes: [],
            notif: "",
            role: ["admin", "client", "reservation"],
          },
          {
            path: "/buyer-management",
            title: "مدیریت خریداران",
            icon: <MdProductionQuantityLimits className="text-2xl" />,
            id: 24384529662,
            isNew: false,
            subRoutes: [],
            notif: "",
            role: ["admin", "client", "reservation"],
          },
        ],
        notif: "",
        role: ["admin", "client", "reservation"],
      },
      {
        path: "/",
        title: "مدیریت صفحات ",
        icon: <SiPagespeedinsights className="text-2xl" />,
        id: 24323422262,
        isNew: false,
        subRoutes: [
          {
            path: "/pages-management",
            title: "مدیریت متن صفحات ",
            icon: <RiPagesLine className="text-2xl" />,
            id: 2432362,
            isNew: false,
            subRoutes: [],
            notif: "",
            role: ["admin", "client", "reservation"],
          },
          {
            path: "/faq-management",
            title: "مدیریت سوالات متداول",
            icon: <FaRegQuestionCircle className="text-2xl" />,
            id: 24323262,
            isNew: false,
            subRoutes: [],
            notif: "",
            role: ["admin", "client", "reservation"],
          },
          {
            path: "/blog-management",
            title: "مدیریت مقالات",
            icon: <RiBloggerLine className="text-2xl" />,
            id: 24012,
            isNew: false,
            subRoutes: [],
            notif: "",
            role: ["admin", "client", "reservation"],
          },
          {
            path: "/blog-category-management",
            title: "مدیریت دسته بندی مقالات",
            icon: <BiCategoryAlt className="text-2xl" />,
            id: 2582,
            isNew: false,
            subRoutes: [],
            notif: "",
            role: ["admin", "client", "reservation"],
          },
        ],
        notif: "",
        role: ["admin", "client", "reservation"],
      },

      {
        path: "/category-management",
        title: "مدیریت دسته بندی",
        icon: <MdOutlineCategory className="text-2xl" />,
        id: 2402,
        isNew: false,
        subRoutes: [],
        notif: "",
        role: ["admin", "client", "reservation"],
      },

      {
        path: "/ticket-management",
        title: "مدیریت تیکت ها",
        icon: <LuTicketPercent className="text-2xl" />,
        id: 240992,
        isNew: false,
        subRoutes: [],
        notif: "",
        role: ["admin", "client", "reservation"],
      },

      {
        path: "/survey-management",
        title: "مدیریت نظرسنجی ها",
        icon: <MdPoll className="text-2xl" />,
        id: 240993,
        isNew: false,
        subRoutes: [],
        notif: "",
        role: ["admin", "client", "reservation"],
      },
    ],
  },

  {
    id: 162,
    isNew: false,
    menuTitle: "مدیریت محصولات",
    order: "1",
    role: ["admin", "client", "reservation"],
    notif: "",
    menus: [
      {
        path: "/product-management",
        title: "مدیریت محصولات",
        icon: <MdOutlineProductionQuantityLimits className="text-2xl" />,
        id: 250181,
        isNew: false,
        subRoutes: [],
        notif: "",
        role: ["admin", "client", "reservation"],
      },

      {
        path: "/shipment-management",
        title: "محاسبه کرایه ناوگان",
        icon: <MdLocalShipping className="text-2xl" />,
        id: 250183,
        isNew: false,
        subRoutes: [],
        notif: "",
        role: ["admin", "client", "reservation"],
      },
      {
        title: "  قیمت گذاری محصول",
        icon: <LuTicketPercent className="text-2xl" />,
        id: 24000992,
        isNew: false,
        notif: "",
        role: ["admin", "client", "reservation"],
        subRoutes: [
          {
            path: "/product-price-management",
            title: "مدیریت قیمت گذاری محصولات",
            icon: <MdOutlineProductionQuantityLimits className="text-2xl" />,
            id: 250182,
            isNew: false,
            subRoutes: [],
            notif: "",
            role: ["admin", "client", "reservation"],
          },
          {
            path: "/purchase-price-management",
            title: "مدیریت قیمت خرید",
            icon: <MdOutlineProductionQuantityLimits className="text-2xl" />,
            id: 250188,
            isNew: false,
            subRoutes: [],
            notif: "",
            role: ["admin", "client", "reservation"],
          },
          {
            path: "/view-pricing-management",
            title: "مشاهده قیمت گذاری",
            icon: <MdOutlineProductionQuantityLimits className="text-2xl" />,
            id: 250189,
            isNew: false,
            subRoutes: [],
            notif: "",
            role: ["admin", "client", "reservation"],
          },
          {
            path: "/price-scrap",
            title: "مشاهده قیمت های بروز",
            icon: <MdOutlineProductionQuantityLimits className="text-2xl" />,
            id: 250190,
            isNew: false,
            subRoutes: [],
            notif: "",
            role: ["admin", "client", "reservation"],
          },
        ],
      },
      {
        title: "اطلاعات پایه قیمت گذاری",
        icon: <LuTicketPercent className="text-2xl" />,
        id: 24001992,
        isNew: false,
        notif: "",
        role: ["admin", "client", "reservation"],
        subRoutes: [
          {
            path: "/pb-product-admin-management",
            title: "تعریف کالا",
            icon: <BsBoxSeam className="text-2xl" />,
            id: 250184,
            isNew: false,
            subRoutes: [],
            notif: "",
            role: ["admin", "client", "reservation"],
          },
          {
            path: "/pb-brand-admin-management",
            title: "مدیریت برند",
            icon: <MdOutlineCategory className="text-2xl" />,
            id: 250185,
            isNew: false,
            subRoutes: [],
            notif: "",
            role: ["admin", "client", "reservation"],
          },
          {
            path: "/pb-provider-admin-management",
            title: "تعریف تامین کنندگان",
            icon: <HiOutlineOfficeBuilding className="text-2xl" />,
            id: 250186,
            isNew: false,
            subRoutes: [],
            notif: "",
            role: ["admin", "client", "reservation"],
          },
          {
            path: "/pb-port-admin-management",
            title: "تعریف محل بارگیری",
            icon: <MdLocalShipping className="text-2xl" />,
            id: 250187,
            isNew: false,
            subRoutes: [],
            notif: "",
            role: ["admin", "client", "reservation"],
          },
        ],
      },
    ],
  },
];


