export const CREATE_USER_ORIGINAL = "CREATE_USER_ORIGINAL";

// create user management
export const CREATE_USER_GET_ALL = "CREATE_USER_GET_ALL";
export const CREATE_USER_GET_BY_ID = "CREATE_USER_GET_BY_ID";
export const CREATE_USER_CREATE = "CREATE_USER_CREATE";
export const CREATE_USER_UPDATE = "CREATE_USER_UPDATE";
export const CREATE_USER_DELETE = "CREATE_USER_DELETE";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";
