import { lazy } from "react";

const routes = [
  {
    path: "/",
    breadCrumb: "درخواست های مناقصه",
    component: lazy(() => import("../page/allRequests")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },

  {
    path: "/product-request-status",
    breadCrumb: "مدیریت وضعیت درخواست ها",
    component: lazy(() => import("../page/productRequestStatus")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/category-management",
    breadCrumb: "مدیریت دسته بندی ها",
    component: lazy(() => import("../page/categoryManagement")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/blog-management",
    breadCrumb: "مدیریت مقالات",
    component: lazy(() => import("../page/blogManagement")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/blog-category-management",
    breadCrumb: "مدیریت دسته بندی مقالات",
    component: lazy(() => import("../page/blogCategoryManagement")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/role-management",
    breadCrumb: "مدیریت نقش ها",
    component: lazy(() => import("../page/roleManagement")),
    layout: "admin",
  },
  {
    path: "/users-management",
    breadCrumb: "مدیریت کاربران",
    component: lazy(() => import("../page/userManagement")),
    layout: "admin",
  },
  {
    path: "/buyer-management",
    breadCrumb: "مدیریت خریداران",
    component: lazy(() => import("../page/buyerManagement")),
    layout: "admin",
  },
  {
    path: "/product-management",
    breadCrumb: "مدیریت محصولات",
    component: lazy(() => import("../page/productManagement")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/product-price-management",
    breadCrumb: "مدیریت قیمت گذاری محصولات",
    component: lazy(() => import("../page/productPriceManagement")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/purchase-price-management",
    breadCrumb: "مدیریت قیمت خرید",
    component: lazy(() => import("../page/purchasePriceManagement")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/view-pricing-management",
    breadCrumb: "مشاهده قیمت گذاری",
    component: lazy(() => import("../page/viewPricingManagement")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/pages-management",
    breadCrumb: "مدیریت صفحات",
    component: lazy(() => import("../page/generalSetting")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/faq-management",
    breadCrumb: "مدیریت سوالات متداول",
    component: lazy(() => import("../page/faqManagement")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/ticket-management",
    breadCrumb: "مدیریت تیکت ها",
    component: lazy(() => import("../page/ticketManagement")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/pending-orders-financial",
    breadCrumb: "سفارشات در انتظار تایید مالی",
    component: lazy(() => import("../page/pendingOrdersFinancial")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/survey-management",
    breadCrumb: "مدیریت نظرسنجی ها",
    component: lazy(() => import("../page/surveyManagement")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/product-requests",
    breadCrumb: "تاریخچه درخواست های مناقصه",
    component: lazy(() => import("../page/productRequests")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/survey-management/edit/:id",
    breadCrumb: "ویرایش نظرسنجی",
    component: lazy(() => import("../page/surveyManagement/SurveyEdit")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/survey-response/:responseId",
    breadCrumb: "جزئیات پاسخ نظرسنجی",
    component: lazy(() => import("../page/surveyResponseDetail")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/shipment-management",
    breadCrumb: "محاسبه کرایه ناوگان",
    component: lazy(() => import("../page/shipmentManagement")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/pb-product-admin-management",
    breadCrumb: "تعریف کالا",
    component: lazy(() => import("../page/pbProductAdminManagement")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/pb-brand-admin-management",
    breadCrumb: "مدیریت برند",
    component: lazy(() => import("../page/pbBrandAdminManagement")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/pb-provider-admin-management",
    breadCrumb: "تعریف تامین کنندگان",
    component: lazy(() => import("../page/pbProviderAdminManagement")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/pb-port-admin-management",
    breadCrumb: "تعریف محل بارگیری",
    component: lazy(() => import("../page/pbPortAdminManagement")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/shop-management",
    breadCrumb: "فروشگاه",
    component: lazy(() => import("../page/shopManagement")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
  {
    path: "/price-scrap",
    breadCrumb: "قیمت واقعی بازار",
    component: lazy(() => import("../page/priceScrap")),
    layout: "admin",
    role: ["admin", "client", "reservation"],
  },
];

export const privateRoutes = [
  {
    path: "/login",
    breadCrumb: "ورود",
    layout: "login",
    component: lazy(() => import("../page/auth/Login")),
    role: null,
  },
  // {
  //   path: "/forget-password",
  //   breadCrumb: "فراموشی رمز عبور",
  //   layout: "login",
  //   component: lazy(() => import("../page/auth/ForgetPassword")),
  //   role: null,
  // },
];

export default routes;
