export const PRODUCT = "PRODUCT";

export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT_STATUS = "UPDATE_PRODUCT_STATUS";
export const CHANGE_PRODUCT_STATUS = "CHANGE_PRODUCT_STATUS";
export const EDIT_PRODUCT_ADMIN = "EDIT_PRODUCT_ADMIN";