export const FOOD_MANAGEMENT_ORIGINAL = "FOOD_MANAGEMENT_ORIGINAL";

// food management
export const FOOD_MANAGEMENT_GET_ALL = "FOOD_MANAGEMENT_GET_ALL";
export const FOOD_MANAGEMENT_GET_BY_ID = "FOOD_MANAGEMENT_GET_BY_ID";
export const FOOD_MANAGEMENT_CREATE = "FOOD_MANAGEMENT_CREATE";
export const FOOD_MANAGEMENT_UPDATE = "FOOD_MANAGEMENT_UPDATE";
export const FOOD_MANAGEMENT_DELETE = "FOOD_MANAGEMENT_DELETE";
