export const PRODUCT_REQUEST_STATUS = "PRODUCT_REQUEST_STATUS";

export const GET_PRODUCT_REQUEST_STATUS = "GET_PRODUCT_REQUEST_STATUS";
export const GET_PRODUCT_REQUEST_BY_ID_STATUS = "GET_PRODUCT_REQUEST_BY_ID_STATUS";
export const UPDATE_PRODUCT_REQUEST_STATUS = "UPDATE_PRODUCT_REQUEST_STATUS";

export const GET_PRODUCT_REQUEST_ADMIN = "GET_PRODUCT_REQUEST_ADMIN";
export const GET_PRODUCT_REQUEST_ADMIN_BY_ID = "GET_PRODUCT_REQUEST_ADMIN_BY_ID";
export const UPDATE_PRODUCT_REQUEST_ADMIN = "UPDATE_PRODUCT_REQUEST_ADMIN";
