export const PRODUCT_REQUEST_STATUS = "PRODUCT_REQUEST_STATUS";

export const GET_PRODUCT_REQUEST_STATUS = "GET_PRODUCT_REQUEST_STATUS";
export const GET_PRODUCT_REQUEST_BY_ID_STATUS = "GET_PRODUCT_REQUEST_BY_ID_STATUS";
export const UPDATE_PRODUCT_REQUEST_STATUS = "UPDATE_PRODUCT_REQUEST_STATUS";
