export const PB_PORT_ADMIN = "PB_PORT_ADMIN";

export const GET_PB_PORT_ADMIN = "GET_PB_PORT_ADMIN";
export const GET_PB_PORT_ADMIN_BY_ID = "GET_PB_PORT_ADMIN_BY_ID";
export const CREATE_PB_PORT_ADMIN = "CREATE_PB_PORT_ADMIN";
export const UPDATE_PB_PORT_ADMIN = "UPDATE_PB_PORT_ADMIN";
export const DELETE_PB_PORT_ADMIN = "DELETE_PB_PORT_ADMIN";