export const APPETIZER_MANAGEMENT_ORIGINAL = "APPETIZER_MANAGEMENT_ORIGINAL";

// food management
export const APPETIZER_MANAGEMENT_GET_ALL = "APPETIZER_MANAGEMENT_GET_ALL";
export const APPETIZER_MANAGEMENT_GET_BY_ID = "APPETIZER_MANAGEMENT_GET_BY_ID";
export const APPETIZER_MANAGEMENT_CREATE = "APPETIZER_MANAGEMENT_CREATE";
export const APPETIZER_MANAGEMENT_UPDATE = "APPETIZER_MANAGEMENT_UPDATE";
export const APPETIZER_MANAGEMENT_DELETE = "APPETIZER_MANAGEMENT_DELETE";
