export const PRODUCT_PRICE = "PRODUCT_PRICE";

export const GET_PRODUCT_PRICE = "GET_PRODUCT_PRICE";
export const GET_PRODUCT_PRICE_BY_ID = "GET_PRODUCT_PRICE_BY_ID";
export const CREATE_PRODUCT_PRICE = "CREATE_PRODUCT_PRICE";
export const UPDATE_PRODUCT_PRICE = "UPDATE_PRODUCT_PRICE";
export const DELETE_PRODUCT_PRICE = "DELETE_PRODUCT_PRICE";
