export const ROLE_MANAGEMENT = "ROLE_MANAGEMENT";

export const GET_ROLE_MANAGEMENT = "GET_ROLE_MANAGEMENT";
export const GET_ROLE_MANAGEMENT_BY_ID = "GET_ROLE_MANAGEMENT_BY_ID";
export const CREATE_ROLE_MANAGEMENT = "CREATE_ROLE_MANAGEMENT";

export const UPDATE_ROLE_MANAGEMENT = "UPDATE_ROLE_MANAGEMENT";
export const DELETE_ROLE_MANAGEMENT = "DELETE_ROLE_MANAGEMENT";

export const ASSIGN_ROLE_MANAGEMENT = "ASSIGN_ROLE_MANAGEMENT";
export const REVOKE_ROLE_MANAGEMENT = "REVOKE_ROLE_MANAGEMENT";

export const GET_PERMISSIONS = "GET_PERMISSIONS";
