export const PB_PRODUCT_ADMIN = "PB_PRODUCT_ADMIN";

export const GET_PB_PRODUCT_ADMIN = "GET_PB_PRODUCT_ADMIN";
export const GET_PB_PRODUCT_ADMIN_BY_ID = "GET_PB_PRODUCT_ADMIN_BY_ID";
export const CREATE_PB_PRODUCT_ADMIN = "CREATE_PB_PRODUCT_ADMIN";
export const UPDATE_PB_PRODUCT_ADMIN = "UPDATE_PB_PRODUCT_ADMIN";
export const DELETE_PB_PRODUCT_ADMIN = "DELETE_PB_PRODUCT_ADMIN";