export const CATEGORY = "CATEGORY";

export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID";
export const CREATE_CATEGORY = "CREATE_CATEGORY";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

export const CEATE_CATEGORY_ATTRIBUTE = "CEATE_CATEGORY_ATTRIBUTE";

export const UPDATE_CATEGORY_ATTRIBUTE = "UPDATE_CATEGORY_ATTRIBUTE";
