export const RESTAURANT_MANAGEMENT_ORIGINAL = "RESTAURANT_MANAGEMENT_ORIGINAL";

// restaurant management
export const RESTAURANT_MANAGEMENT_GET_ALL = "RESTAURANT_MANAGEMENT_GET_ALL";
export const RESTAURANT_MANAGEMENT_GET_BY_ID =
  "RESTAURANT_MANAGEMENT_GET_BY_ID";
export const RESTAURANT_MANAGEMENT_CREATE = "RESTAURANT_MANAGEMENT_CREATE";
export const RESTAURANT_MANAGEMENT_UPDATE = "RESTAURANT_MANAGEMENT_UPDATE";
export const RESTAURANT_MANAGEMENT_DELETE = "RESTAURANT_MANAGEMENT_DELETE";
