export const BLOG_CATEGORY = "BLOG_CATEGORY";

export const GET_BLOG_CATEGORY = "GET_BLOG_CATEGORY";
export const GET_BLOG_CATEGORY_BY_ID = "GET_BLOG_CATEGORY_BY_ID";
export const CREATE_BLOG_CATEGORY = "CREATE_BLOG_CATEGORY";

export const UPDATE_BLOG_CATEGORY = "UPDATE_BLOG_CATEGORY";
export const DELETE_BLOG_CATEGORY = "DELETE_BLOG_CATEGORY";
