export const SOCKET_ORIGINAL = "SOCKET_ORIGINAL";

//get message
export const SOCKET_GET_MESSAGE = "SOCKET_GET_MESSAGE";
export const SOCKET_GET_CURRENT_CHATS = "SOCKET_GET_CURRENT_CHATS";
export const SOCKET_IS_TYPING = "SOCKET_IS_TYPING";
export const SOCKET_GET_ONLINE_CONTACTS_USERS =
  "SOCKET_GET_ONLINE_CONTACTS_USERS";
export const SOCKET_PROGRESS_UPLOAD = "SOCKET_PROGRESS_UPLOAD";
export const SOCKET_STOP_DOWNLOAD = "SOCKET_STOP_DOWNLOAD";
export const SOCKET_REMOVE_MESSAGE = "SOCKET_REMOVE_MESSAGE";
