export const GENERAL_SETTING = "GENERAL_SETTING";

export const GET_GENERAL_SETTING = "GET_GENERAL_SETTING";
export const CREATE_GENERAL_SETTING = "CREATE_GENERAL_SETTING";

export const UPDATE_GENERAL_SETTING = "UPDATE_GENERAL_SETTING";
export const DELETE_GENERAL_SETTING = "DELETE_GENERAL_SETTING";
