export const ADMIN_FOOD_RESERVE_ORIGINAL = "FOOD_RESERVE_ORIGINA";

// food reserve management
export const ADMIN_FOOD_RESERVE_GET_ALL = "ADMIN_FOOD_RESERVE_GET_ALL";
export const ADMIN_FOOD_RESERVE_EXPORT = "ADMIN_FOOD_RESERVE_EXPORT";
export const ADMIN_FOOD_RESERVE_GET_BY_ID = "ADMIN_FOOD_RESERVE_GET_BY_ID";
export const ADMIN_FOOD_RESERVE_CREATE = "ADMIN_FOOD_RESERVE_CREATE";
export const ADMIN_FOOD_RESERVE_UPDATE = "ADMIN_FOOD_RESERVE_UPDATE";
export const ADMIN_FOOD_RESERVE_DELETE = "ADMIN_FOOD_RESERVE_DELETE";
