export const FOOD_RESERVE_ORIGINAL = "FOOD_RESERVE_ORIGINA";

// food reserve management
export const CLIENT_FOOD_RESERVE_GET_ALL = "CLIENT_FOOD_RESERVE_GET_ALL";
export const CLIENT_FOOD_RESERVE_CREATE = "CLIENT_FOOD_RESERVE_CREATE";
export const CLIENT_FOOD_RESERVE_DELETE = "CLIENT_FOOD_RESERVE_DELETE";

// current user history
export const GET_CURRENT_USER_HISTORY = "GET_CURRENT_USER_HISTORY";
