export const PB_PROVIDER_ADMIN = "PB_PROVIDER_ADMIN";

export const GET_PB_PROVIDER_ADMIN = "GET_PB_PROVIDER_ADMIN";
export const GET_PB_PROVIDER_ADMIN_BY_ID = "GET_PB_PROVIDER_ADMIN_BY_ID";
export const CREATE_PB_PROVIDER_ADMIN = "CREATE_PB_PROVIDER_ADMIN";
export const UPDATE_PB_PROVIDER_ADMIN = "UPDATE_PB_PROVIDER_ADMIN";
export const DELETE_PB_PROVIDER_ADMIN = "DELETE_PB_PROVIDER_ADMIN";