export const PRODUCT_REQUEST_OFFER = "PRODUCT_REQUEST_OFFER";

export const GET_PRODUCT_REQUEST_OFFER = "GET_PRODUCT_REQUEST_OFFER";
export const GET_PRODUCT_REQUEST_BY_ID_OFFER =
  "GET_PRODUCT_REQUEST_BY_ID_OFFER";

export const UPDATE_PRODUCT_REQUEST_OFFER = "UPDATE_PRODUCT_REQUEST_OFFER";
export const UPDATE_PRODUCT_REQUEST_SEND_TO_BUYER_OFFER =
  "UPDATE_PRODUCT_REQUEST_SEND_TO_BUYER_OFFER";
