export const FOOD_CATEGORY_ORIGINAL = "FOOD_CATEGORY_ORIGINAL";

// food reservation management
export const FOOD_CATEGORY_GET_ALL = "FOOD_CATEGORY_GET_ALL";
export const FOOD_CATEGORY_GET_BY_ID = "FOOD_CATEGORY_GET_BY_ID";
export const FOOD_CATEGORY_CREATE = "FOOD_CATEGORY_CREATE";
export const FOOD_CATEGORY_UPDATE = "FOOD_CATEGORY_UPDATE";
export const FOOD_CATEGORY_DELETE = "FOOD_CATEGORY_DELETE";
