export const PB_BRAND_ADMIN = "PB_BRAND_ADMIN";

export const GET_PB_BRAND_ADMIN = "GET_PB_BRAND_ADMIN";
export const GET_PB_BRAND_ADMIN_BY_ID = "GET_PB_BRAND_ADMIN_BY_ID";
export const CREATE_PB_BRAND_ADMIN = "CREATE_PB_BRAND_ADMIN";
export const UPDATE_PB_BRAND_ADMIN = "UPDATE_PB_BRAND_ADMIN";
export const DELETE_PB_BRAND_ADMIN = "DELETE_PB_BRAND_ADMIN";