export const REQUEST_ORDER = "requestOrder";
export const GET_REQUEST_ORDER_ADMIN = "GET_REQUEST_ORDER_ADMIN";
export const APPROVE_REQUEST_ORDER = "APPROVE_REQUEST_ORDER";
export const REJECT_REQUEST_ORDER = "REJECT_REQUEST_ORDER";
export const VERIFY_REQUEST_PAYMENT = "VERIFY_REQUEST_PAYMENT";
export const MAKE_REQUEST_DELIVERED = "MAKE_REQUEST_DELIVERED";